using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PresentationLayer.enums
{
    using System.ComponentModel;

    public enum EnumCities
    {
        [Description("Bakar")] Bakar,
        [Description("Beli Manastir")] BeliManastir,
        [Description("Belišće")] Belisce,
        [Description("Benkovac")] Benkovac,
        [Description("Biograd na Moru")] BiogradNaMoru,
        [Description("Bjelovar")] Bjelovar,
        [Description("Buje")] Buje,
        [Description("Buzet")] Buzet,
        [Description("Cres")] Cres,
        [Description("Crikvenica")] Crikvenica,
        [Description("Čabar")] Cabar,
        [Description("Čakovec")] Cakovec,
        [Description("Čazma")] Cazma,
        [Description("Daruvar")] Daruvar,
        [Description("Delnice")] Delnice,
        [Description("Donja Stubica")] DonjaStubica,
        [Description("Donji Miholjac")] DonjiMiholjac,
        [Description("Drniš")] Drnis,
        [Description("Dubrovnik")] Dubrovnik,
        [Description("Duga Resa")] DugaResa,
        [Description("Dugo Selo")] DugoSelo,
        [Description("Đakovo")] Dakovo,
        [Description("Đurđevac")] Durdevac,
        [Description("Garešnica")] Garesnica,
        [Description("Glina")] Glina,
        [Description("Gospić")] Gospic,
        [Description("Grubišno Polje")] GrubisnoPolje,
        [Description("Hrvatska Kostajnica")] HrvatskaKostajnica,
        [Description("Hvar")] Hvar,
        [Description("Ilok")] Ilok,
        [Description("Imotski")] Imotski,
        [Description("Ivanec")] Ivanec,
        [Description("Ivanić-Grad")] IvanicGrad,
        [Description("Jastrebarsko")] Jastrebarsko,
        [Description("Karlovac")] Karlovac,
        [Description("Kastav")] Kastav,
        [Description("Kaštela")] Kastela,
        [Description("Klanjec")] Klanjec,
        [Description("Knin")] Knin,
        [Description("Komiža")] Komiza,
        [Description("Koprivnica")] Koprivnica,
        [Description("Korčula")] Korcula,
        [Description("Kraljevica")] Kraljevica,
        [Description("Krapina")] Krapina,
        [Description("Križevci")] Krizevci,
        [Description("Krk")] Krk,
        [Description("Kutina")] Kutina,
        [Description("Kutjevo")] Kutjevo,
        [Description("Labin")] Labin,
        [Description("Lepoglava")] Lepoglava,
        [Description("Lipik")] Lipik,
        [Description("Ludbreg")] Ludbreg,
        [Description("Makarska")] Makarska,
        [Description("Mali Lošinj")] MaliLosinj,
        [Description("Metković")] Metkovic,
        [Description("Mursko Središće")] MurskoSredisce,
        [Description("Našice")] Nasice,
        [Description("Nin")] Nin,
        [Description("Nova Gradiška")] NovaGradiska,
        [Description("Novalja")] Novalja,
        [Description("Novi Marof")] NoviMarof,
        [Description("Novi Vinodolski")] NoviVinodolski,
        [Description("Novigrad")] Novigrad,
        [Description("Novska")] Novska,
        [Description("Obrovac")] Obrovac,
        [Description("Ogulin")] Ogulin,
        [Description("Omiš")] Omis,
        [Description("Opatija")] Opatija,
        [Description("Opuzen")] Opuzen,
        [Description("Orahovica")] Orahovica,
        [Description("Oroslavje")] Oroslavje,
        [Description("Osijek")] Osijek,
        [Description("Otočac")] Otocac,
        [Description("Otok")] Otok,
        [Description("Ozalj")] Ozalj,
        [Description("Pag")] Pag,
        [Description("Pakrac")] Pakrac,
        [Description("Pazin")] Pazin,
        [Description("Petrinja")] Petrinja,
        [Description("Pleternica")] Pleternica,
        [Description("Ploče")] Ploce,
        [Description("Popovača")] Popovaca,
        [Description("Poreč")] Porec,
        [Description("Požega")] Pozega,
        [Description("Pregrada")] Pregrada,
        [Description("Prelog")] Prelog,
        [Description("Pula")] Pula,
        [Description("Rab")] Rab,
        [Description("Rijeka")] Rijeka,
        [Description("Rovinj")] Rovinj,
        [Description("Samobor")] Samobor,
        [Description("Senj")] Senj,
        [Description("Sinj")] Sinj,
        [Description("Sisak")] Sisak,
        [Description("Skradin")] Skradin,
        [Description("Slatina")] Slatina,
        [Description("Slavonski Brod")] SlavonskiBrod,
        [Description("Slunj")] Slunj,
        [Description("Solin")] Solin,
        [Description("Split")] Split,
        [Description("Stari Grad")] StariGrad,
        [Description("Supetar")] Supetar,
        [Description("Sveta Nedelja")] SvetaNedelja,
        [Description("Sveti Ivan Zelina")] SvetiIvanZelina,
        [Description("Šibenik")] Sibenik,
        [Description("Trilj")] Trilj,
        [Description("Trogir")] Trogir,
        [Description("Umag")] Umag,
        [Description("Valpovo")] Valpovo,
        [Description("Varaždin")] Varazdin,
        [Description("Varaždinske Toplice")] VarazdinskeToplice,
        [Description("Velika Gorica")] VelikaGorica,
        [Description("Vinkovci")] Vinkovci,
        [Description("Virovitica")] Virovitica,
        [Description("Vis")] Vis,
        [Description("Vodice")] Vodice,
        [Description("Vodnjan")] Vodnjan,
        [Description("Vrbovec")] Vrbovec,
        [Description("Vrbovsko")] Vrbovsko,
        [Description("Vrgorac")] Vrgorac,
        [Description("Vrlika")] Vrlika,
        [Description("Vukovar")] Vukovar,
        [Description("Zabok")] Zabok,
        [Description("Zadar")] Zadar,
        [Description("Zagreb")] Zagreb,
        [Description("Zaprešić")] Zapresic,
        [Description("Zlatar")] Zlatar,
        [Description("Županja")] Zupanja
    }

}
